name: build

on: [push, pull_request]

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.5', '8.4', '8.3']

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov

    - run: composer install
    - run: composer lint
    - run: composer test
    - if: github.event_name != 'pull_request'
      run: php vendor/bin/php-coveralls -v
